"use client";

import { useState, useCallback } from "react";

function generateCode(imageUrl: string): string {
  return `"use client";

// ─────────────────────────────────────────────────────────────────────────────
// Auto-generated by 3D Fragment FX Generator
// Requires: @react-three/fiber  @react-three/drei  three  gsap
// Usage: drop <FragmentScene /> anywhere in your Next.js App Router project.
// ─────────────────────────────────────────────────────────────────────────────

import { useEffect, useRef, useMemo } from "react";
import { Canvas, useFrame, useThree } from "@react-three/fiber";
import * as THREE from "three";
import gsap from "gsap";
import ScrollTrigger from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

const GRID = 8;
const COUNT = GRID * GRID;
const TILE_SIZE = 0.9;
const GAP = 1.0;
const SCATTER_Z = -20;

const vertexShader = \`
  attribute vec2 uvOffset;
  varying vec2 vUv;
  void main() {
    float tileSize = 1.0 / \${GRID}.0;
    vUv = uvOffset + uv * tileSize;
    vec4 mvPos = modelViewMatrix * instanceMatrix * vec4(position, 1.0);
    gl_Position = projectionMatrix * mvPos;
  }
\`;

const fragmentShader = \`
  uniform sampler2D uTexture;
  uniform float uOpacity;
  varying vec2 vUv;
  void main() {
    vec4 color = texture2D(uTexture, vUv);
    gl_FragColor = vec4(color.rgb, color.a * uOpacity);
  }
\`;

function Fragments({ texture, scrollProgress }) {
  const meshRef = useRef(null);
  const { camera } = useThree();

  const { uvOffsets, targetMatrices, scatterMatrices } = useMemo(() => {
    const uvOffsets = new Float32Array(COUNT * 2);
    const targetMatrices = [];
    const scatterMatrices = [];
    const totalW = (GRID - 1) * GAP;
    const totalH = (GRID - 1) * GAP;

    for (let row = 0; row < GRID; row++) {
      for (let col = 0; col < GRID; col++) {
        const i = row * GRID + col;
        uvOffsets[i * 2 + 0] = col / GRID;
        uvOffsets[i * 2 + 1] = (GRID - 1 - row) / GRID;

        const tx = col * GAP - totalW / 2;
        const ty = row * GAP - totalH / 2;
        targetMatrices.push(
          new THREE.Matrix4().compose(
            new THREE.Vector3(tx, ty, 0),
            new THREE.Quaternion(),
            new THREE.Vector3(1, 1, 1)
          )
        );

        scatterMatrices.push(
          new THREE.Matrix4().compose(
            new THREE.Vector3(
              (Math.random() - 0.5) * totalW * 2.5,
              (Math.random() - 0.5) * totalH * 2.5,
              SCATTER_Z + Math.random() * 10
            ),
            new THREE.Quaternion().setFromEuler(
              new THREE.Euler(
                (Math.random() - 0.5) * Math.PI * 2,
                (Math.random() - 0.5) * Math.PI * 2,
                (Math.random() - 0.5) * Math.PI
              )
            ),
            new THREE.Vector3(1, 1, 1)
          )
        );
      }
    }
    return { uvOffsets, targetMatrices, scatterMatrices };
  }, []);

  useEffect(() => {
    if (!meshRef.current) return;
    meshRef.current.geometry.setAttribute(
      "uvOffset",
      new THREE.InstancedBufferAttribute(uvOffsets, 2)
    );
    for (let i = 0; i < COUNT; i++) {
      meshRef.current.setMatrixAt(i, scatterMatrices[i]);
    }
    meshRef.current.instanceMatrix.needsUpdate = true;
  }, [uvOffsets, scatterMatrices]);

  const tmp = useMemo(() => new THREE.Matrix4(), []);
  const posA = useMemo(() => new THREE.Vector3(), []);
  const posB = useMemo(() => new THREE.Vector3(), []);
  const quatA = useMemo(() => new THREE.Quaternion(), []);
  const quatB = useMemo(() => new THREE.Quaternion(), []);
  const scaleA = useMemo(() => new THREE.Vector3(), []);
  const scaleB = useMemo(() => new THREE.Vector3(), []);

  useFrame(() => {
    const t = scrollProgress.current;
    const p = t * t * (3 - 2 * t);
    for (let i = 0; i < COUNT; i++) {
      scatterMatrices[i].decompose(posA, quatA, scaleA);
      targetMatrices[i].decompose(posB, quatB, scaleB);
      posA.lerp(posB, p);
      quatA.slerp(quatB, p);
      scaleA.lerp(scaleB, p);
      tmp.compose(posA, quatA, scaleA);
      meshRef.current.setMatrixAt(i, tmp);
    }
    meshRef.current.instanceMatrix.needsUpdate = true;
  });

  useEffect(() => {
    camera.position.set(0, 0, 8);
    camera.lookAt(0, 0, 0);
  }, [camera]);

  const material = useMemo(
    () =>
      new THREE.ShaderMaterial({
        uniforms: {
          uTexture: { value: texture },
          uOpacity: { value: 1.0 },
        },
        vertexShader,
        fragmentShader,
        transparent: true,
        side: THREE.DoubleSide,
      }),
    [texture]
  );

  const geometry = useMemo(() => new THREE.PlaneGeometry(TILE_SIZE, TILE_SIZE), []);

  return (
    <instancedMesh
      ref={meshRef}
      args={[geometry, material, COUNT]}
      frustumCulled={false}
    />
  );
}

function ScrollBinder({ scrollProgress }) {
  useEffect(() => {
    const trigger = ScrollTrigger.create({
      trigger: document.body,
      start: "top top",
      end: "bottom bottom",
      onUpdate: (self) => {
        scrollProgress.current = self.progress;
      },
    });
    return () => trigger.kill();
  }, [scrollProgress]);
  return null;
}

export default function FragmentScene() {
  const scrollProgress = useRef(0);

  const texture = useMemo(() => {
    const tex = new THREE.TextureLoader().load(
      "${imageUrl.length > 120 ? imageUrl.slice(0, 120) + "…[base64 data]" : imageUrl}"
    );
    tex.colorSpace = THREE.SRGBColorSpace;
    return tex;
  }, []);

  return (
    // Wrap in a tall container so there is room to scroll
    <div style={{ height: "300vh", position: "relative" }}>
      <div style={{ position: "sticky", top: 0, width: "100%", height: "100vh" }}>
        <Canvas
          gl={{ antialias: true, alpha: true }}
          dpr={[1, 2]}
          camera={{ fov: 60, near: 0.1, far: 200 }}
          style={{ background: "#0a0a0f" }}
        >
          <ambientLight intensity={1.5} />
          <ScrollBinder scrollProgress={scrollProgress} />
          <Fragments texture={texture} scrollProgress={scrollProgress} />
        </Canvas>
      </div>
    </div>
  );
}
`;
}

interface CodeExporterProps {
  imageUrl: string | null;
}

export default function CodeExporter({ imageUrl }: CodeExporterProps) {
  const [copied, setCopied] = useState(false);
  const [open, setOpen] = useState(false);

  const code = imageUrl ? generateCode(imageUrl) : "";

  const handleCopy = useCallback(() => {
    if (!code) return;
    navigator.clipboard.writeText(code).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [code]);

  if (!imageUrl) return null;

  return (
    <div className="w-full max-w-4xl mx-auto mt-6">
      <button
        onClick={() => setOpen((v) => !v)}
        className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 border border-slate-700 hover:border-violet-500 text-slate-300 hover:text-white transition-all text-sm font-medium"
      >
        <svg className={`w-4 h-4 transition-transform ${open ? "rotate-90" : ""}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" />
        </svg>
        {open ? "Hide generated code" : "View generated code"}
      </button>

      {open && (
        <div className="mt-3 rounded-2xl border border-slate-700 bg-slate-950 overflow-hidden shadow-2xl">
          <div className="flex items-center justify-between px-4 py-2 bg-slate-900 border-b border-slate-700">
            <div className="flex gap-1.5">
              <span className="w-3 h-3 rounded-full bg-red-500/70" />
              <span className="w-3 h-3 rounded-full bg-yellow-500/70" />
              <span className="w-3 h-3 rounded-full bg-green-500/70" />
            </div>
            <span className="text-xs text-slate-500 font-mono">FragmentScene.tsx</span>
            <button
              onClick={handleCopy}
              className={`flex items-center gap-1.5 text-xs px-3 py-1 rounded-lg transition-all ${
                copied
                  ? "bg-green-500/20 text-green-400 border border-green-500/30"
                  : "bg-slate-800 text-slate-400 hover:text-white border border-slate-700 hover:border-violet-500"
              }`}
            >
              {copied ? (
                <>
                  <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                  </svg>
                  Copied!
                </>
              ) : (
                <>
                  <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                  </svg>
                  Copy code
                </>
              )}
            </button>
          </div>
          <pre className="overflow-x-auto overflow-y-auto max-h-[60vh] p-4 text-xs leading-relaxed text-slate-300 font-mono">
            <code>{code}</code>
          </pre>
        </div>
      )}
    </div>
  );
}
